version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing backend dependencies...
      - cd BackEnd
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running migrations...
      - python manage.py migrate
  build:
    commands:
      - echo Collecting static files...
      - python manage.py runserver
artifacts:
  files:
    - "BackEnd/**/*"
  base-directory: BackEnd
