version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.15.1
    commands:
      - echo Installing frontend dependencies...
      - cd reactfrontend
      - npm install || echo "No package.json file found"
  pre_build:
    commands:
      - echo Running frontend pre-build steps...
  build:
    commands:
      - echo Building frontend...
      - npm run build
  post_build:
    commands:
    - echo Frontend build complete.
    - echo newww
artifacts:
  files:
    - "**/*"
  base-directory: reactfrontend
