version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.15.1
    commands:
      - echo Installing frontend dependencies...
      - cd reactfrontend
      - npm install || echo "No package.json file found"
  pre_build:
    commands:
      - echo Running frontend pre-build steps...
  build:
    commands:
      - echo Building frontend...
      - npm run build
  post_build:
    commands:
      - echo Frontend build complete.
      # - echo Emptying S3 bucket...
      # - aws s3 rm s3://my-react-frontend-bucket --recursive
      # - echo Uploading build artifacts to S3 bucket...
      # - aws s3 cp build s3://my-react-frontend-bucket --recursive
artifacts:
  files:
    - "**/*"
  base-directory: reactfrontend/build
